name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TWITTER_CONSUMER_TOKEN_KEY: ${{ secrets.TWITTER_CONSUMER_TOKEN_KEY }}
  TWITTER_CONSUMER_TOKEN_SECRET: ${{ secrets.TWITTER_CONSUMER_TOKEN_SECRET }}
  TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt test
